rake:
  script:
  - git submodule update --init
  - ls -la
  - gem install bundler
  - bundle config --global jobs 4
  - bundle config --global path /cache/gems
  - bundle config build.nokogiri "--use-system-libraries --with-xml2-include=/usr/include/libxml2"
  - bundle check || bundle install
  - bundle exec rake
  tags:
  - ruby